### PR TITLE
Fix: Large fast forward/rewind value popup on player

### LINKED ISSUE #8230: [Bug]: Large fast forward/rewind popup on player
### Guidelines

- [x] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [x] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [x] I have [searched the issue tracker for open and closed issues](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+sort%3Arelevance-desc) that are similar to the bug report I want to file, without success.
- [x] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [x] This issue contains only one bug.
- [x] I have read and agree to follow the [rules](https://docs.freetubeapp.io/community/rules/).

### Describe the bug

1. Go to Player settings
2. Set `Fast-Forward / Rewind Interval` to 13s
3. Watch a video
4. Set the playback speed to 1.8x
5. Use ←, →, J and L
6. See large popup

https://github.com/user-attachments/assets/9edefa6f-6589-4f5d-bf33-3d292c422d97

### Expected Behavior

Make number smaller max two decimal places

### Issue Labels

inconsistent behavior, visual bug

### FreeTube Version

v0.23.12-nightly-6602 Beta

### Operating System Version

Windows 11 IoT Enterprise LTSC 24H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

_No response_

### Additional Information

_No response_

### Nightly Build

- [x] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

### PR DESCRIPTION
**Pull request by ozrendev**
## Pull Request Type

- [x] Bugfix
- [ ] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

closes #8230 

## Description

Rounds `formattedSeconds` to two decimal places to avoid a very long displayed value

## Testing

Go to Player settings
Set Video Playback Rate Interval to 0.1
Set Fast-Forward / Rewind Interval to 13s
Set the playback speed to 1.8x
Watch a video
Use ←, →, J and L
See playback rate popup showing rounded number

### CODE REVIEW

File: src/renderer/components/ft-shaka-video-player/ft-shaka-video-player.js [hunk 1]
```diff
@@ -1966,7 +1966,7 @@ export default defineComponent({
         const popUpLayout = seconds > 0
           ? { icon: 'arrow-right', invertContentOrder: true }
           : { icon: 'arrow-left', invertContentOrder: false }
-        const formattedSeconds = Math.abs(seconds)
+        const formattedSeconds = Math.abs(seconds).toFixed(2)
```
Comment (PikachuEXE) [inline src/renderer/components/ft-shaka-video-player/ft-shaka-video-player.js]: My solution for avoiding `10.00` from https://github.com/FreeTubeApp/FreeTube/pull/8047
```suggestion
        // `+value` converts string back to float
        const formattedSeconds = +Math.abs(seconds).toFixed(2)
```
