### PR TITLE
Handle IP blocks better on the watch page

### LINKED ISSUE #5534: [Bug]: Both Local and Individuous API don't work. Pulling Null of Video
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Whenever attempting to open a video, I am greeted by messages that say:

"Local API Error: Type Error: Cannot read properties of null (reading 'reason'). Then, Invidious API error: Error: Missing harsh key "videoDetails"

I cannot get any videos to play
Screenshot 2024-08-06 at 1 42 26 PM

### Expected Behavior

I would expect to click the video link and have the video play.

### Issue Labels

API issue

### FreeTube Version

v0.21.3 Beta

### Operating System Version

macOS Sonoma 14.6

### Installation Method

.dmg

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.1 Beta

### Additional Information

_No response_

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

### PR DESCRIPTION
**Pull request by absidue**
# Handle IP blocks better on the watch page

## Pull Request Type

- [x] Bugfix

## Related issue
closes #5534

## Description
This pull request fixes the `TypeError: Cannot read properties of null (reading 'reason')` error message by correcting where we get the `reason` property from and by adding a proper error message when the users is IP blocked.

This changes in this pull request are based on the response files provided in this comment https://github.com/FreeTubeApp/FreeTube/issues/5534#issuecomment-2323469591, as I haven't found an IP address that is blocked and nobody responded to this comment asking for information on how to find a blocked IP https://github.com/FreeTubeApp/FreeTube/issues/5534#issuecomment-2367410051

## Testing
I have not been able to test this, as I haven't found an IP address that is blocked and nobody responded to this comment asking for information on how to find a blocked IP https://github.com/FreeTubeApp/FreeTube/issues/5534#issuecomment-2367410051

## Desktop

- **OS:** Windows
- **OS Version:** 10
- **FreeTube version:** 30f95e5700ac57bc18700fa24e64af91fd3388f4

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
As our team cant didnt ran into the IP blocks maybe create test build and provide it to the users of that issue?

File: src/renderer/views/Watch/Watch.js [hunk 1]
```diff
@@ -358,12 +358,18 @@ export default defineComponent({
 
         const playabilityStatus = result.playability_status
 
-        if (playabilityStatus.status === 'UNPLAYABLE') {
-          /**
-           * @type {import ('youtubei.js').YTNodes.PlayerErrorMessage}
-           */
-          const errorScreen = playabilityStatus.error_screen
-          throw new Error(`[${playabilityStatus.status}] ${errorScreen.reason.text}: ${errorScreen.subreason.text}`)
+        if (playabilityStatus.status === 'UNPLAYABLE' || (playabilityStatus.status === 'LOGIN_REQUIRED' && playabilityStatus.reason === 'Sign in to confirm you are not a bot')) {
```
Comment (efb4f5ff-1298-471a-8973-3d47447115dc) [inline src/renderer/views/Watch/Watch.js:361]:
```suggestion
        if (playabilityStatus.status === 'UNPLAYABLE' || (playabilityStatus.status === 'LOGIN_REQUIRED' && playabilityStatus.reason === 'Sign in to confirm you're not a bot')) {
```

File: src/renderer/views/Watch/Watch.js [hunk 2]
```diff
@@ -358,12 +358,18 @@ export default defineComponent({
...
+          if (playabilityStatus.reason === 'Sign in to confirm you are not a bot') {
```
Comment (efb4f5ff-1298-471a-8973-3d47447115dc) [inline src/renderer/views/Watch/Watch.js:362]:
```suggestion
          if (playabilityStatus.reason === 'Sign in to confirm you're not a bot') {
```

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]
Found a blocked IP. LGTM!

**Review by ChunkyProgrammer — APPROVED** [review]

**Review by PikachuEXE — APPROVED** [review]

**Comment by daiyam** [comment]
Hi, I was wondering if we can improve the error message since it isn't clear that the error is due to a BOT verification from youtube.

I'm getting that error while I don't use a VPN. Same as #7159.
I've figured out the issue when using `youtube-dl`. It gave me a clearer message (`You are suspected as a bot. Wait, or pass the captcha test on the site and provide --cookies.`).

Also, is there a way to give cookies like the `--cookies-from-browser` option from `youtube-dl`?
