### PR TITLE
Use raw query for suggestions

### LINKED ISSUE #7443: [Bug]: Search History incorrectly includes first search suggestion
### Guidelines

- [x] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [x] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [x] I have [searched the issue tracker for open and closed issues](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+sort%3Arelevance-desc) that are similar to the bug report I want to file, without success.
- [x] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [x] This issue contains only one bug.

### Describe the bug

1. Search something
2. Click on search bar
3. Press spacebar
4. See that it thinks that the first search suggestion is part of the search history

https://github.com/user-attachments/assets/3e09216b-9110-4c5e-bd21-aadcac16c387

### Expected Behavior

Do not include search suggestion in search history

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.23.5-nightly-6042 Beta

### Operating System Version

Windows 11 IoT Enterprise LTSC 24H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

_No response_

### Additional Information

_No response_

### Nightly Build

- [x] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

### PR DESCRIPTION
**Pull request by caetano-dev**
## Pull Request Type

- [x] Bugfix
- [ ] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

Closes #7443 

## Description

Fixes a bug that would incorrectly tag search suggestion as part of the search history.

### Before:

My search history:

Searching for "cpu"

before0

Searching for "cpu " (empty space at the end, showing "cpu cooler" as if it were part of my search history)

before1

---

### After:

Searching for "cpu"

Searching for "cpu " ("cpu cooler" no longer shows as part of my search history)

## Testing

1. Search something
2. Click on search bar
3. Press spacebar
4. See that it no longer shows the first search suggestion as part of the search history.

## Desktop

- **OS:** Linux
- **OS Version:** Ubuntu 24.04.2 LTS
- **FreeTube version:** v0.23.5 Beta

### CODE REVIEW

**Review by PikachuEXE — APPROVED** [review]

File: src/renderer/components/TopNav/TopNav.vue [hunk 1]
```diff
@@ -524,11 +524,11 @@ function updateSearchInputText(text) {
...
-  if (trimmedQuery === lastSuggestionQuery.value) {
+  if (query === lastSuggestionQuery.value) {
     return
   }
 
-  lastSuggestionQuery.value = trimmedQuery
+  lastSuggestionQuery.value = query
 
   if (enableSearchSuggestions.value) {
     debounceSearchResults(trimmedQuery)
```
Comment (absidue) [inline src/renderer/components/TopNav/TopNav.vue]:
```suggestion
    debounceSearchResults(query.trim())
```

File: src/renderer/components/TopNav/TopNav.vue [hunk 2]
```diff
@@ -524,11 +524,11 @@ function updateSearchInputText(text) {
  */
 function getSearchSuggestionsDebounce(query) {
   const trimmedQuery = query.trim()
```
Comment (absidue) [inline src/renderer/components/TopNav/TopNav.vue]:
```suggestion
```

**Review by absidue — COMMENTED** [review]
As the `trimmedQuery` variable is only used in a single place after this change, we can inline it.

**Comment by caetano-dev** [comment]
I applied the suggested changes for the `trimmedQuery` const.

**Review by PikachuEXE — APPROVED** [review]
