### PR TITLE
Fix Hide Channel Subscribers setting still displaying subscribers if changed from a secondary window (#3504)

### LINKED ISSUE #3504: [Bug]: Subsciber count not hidden in subscribe button on video page when `Hide Channel Subscribers` is enabled
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Enable `Hide Channel Subscribers` in Distraction Free Settings
2. Go to a video of a channel u are not subscribed to
3. See subscriber count in subscribe button

https://user-images.githubusercontent.com/73130443/236695299-178eea7d-b5e2-494d-99bd-b9d772b62b3a.mp4

### Expected Behavior

Subscription should be hidden in subscribe button on video page when `Hide Channel Subscribers` is enabled

### Issue Labels

inconsistent behavior

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/6ef572d1fae8043e9c223ce9f8a32b00b29b2539

### Operating System Version

Win10 22H2

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

_No response_

### Additional Information

_No response_

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

### PR DESCRIPTION
**Pull request by Rikthepixel**
# Fix Hide Channel Subscribers setting still displaying subscribers if changed from a secondary window (#3504)

## Pull Request Type
- [x] Bugfix
- [ ] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue
closes #3504

## Description
I fixed this issue in 3 components:

1. ft-list-channel
2. watch-video-info
3. Channel

Because `hideChannelSubscriptions` is state that can be updated, the places where this was implemented did not seem to take that into account. 

For example, in the Channel.js the getChannelLocal only gets called when the component is mounted. In that method they are setting the `this.subCount` state to `null` if `hideChannelSubscriptions` is `false`. Normally this would not be an issue because the component would be remounted if you go back and forth between pages, but because we have two windows open that means the `this.subCount` value will always stay null.

There may be some other "distraction free settings" that have the same issues. Although unless someone uses two windows simultaneously it should be barely an issue. 

## Screenshots
(Example channel page)

### Before:
before

### After:
afbeelding

## Testing
I hand tested this issue by switching the `Hide Channel Subscribers` on/off.

## Desktop
- **OS:** Windows 11
- **OS Version:** 22H2
- **FreeTube version:** Release 0.18.0 Beta

### CODE REVIEW

File: src/renderer/components/watch-video-info/watch-video-info.js [hunk 1]
```diff
@@ -43,10 +47,6 @@ export default defineComponent({
       type: Number,
       required: true
     },
-    subscriptionCountText: {
```
Comment (PikachuEXE) [inline src/renderer/components/watch-video-info/watch-video-info.js:46]: Please revert naming changes which is unnecessary to make this work

File: src/renderer/components/watch-video-info/watch-video-info.js [hunk 2]
```diff
@@ -105,11 +105,11 @@ export default defineComponent({
     }
   },
   computed: {
-    hideSharingActions: function() {
+    hideSharingActions: function () {
```
Comment (PikachuEXE) [inline src/renderer/components/watch-video-info/watch-video-info.js:108]: Please revert unnecessary space changes

File: src/renderer/components/ft-list-channel/ft-list-channel.js [hunk 3]
```diff
@@ -53,11 +53,8 @@ export default defineComponent({
 
       this.channelName = this.data.name
       this.id = this.data.id
-      if (this.hideChannelSubscriptions || this.data.subscribers == null) {
-        this.subscriberCount = null
-      } else {
-        this.subscriberCount = this.data.subscribers.replace(/ subscriber(s)?/, '')
-      }
+      this.subscriberCount = this.data.subscribers !== null ? this.data.subscribers.replace(/ subscriber(s)?/, '') : ''
```
Comment (PikachuEXE) [inline src/renderer/components/ft-list-channel/ft-list-channel.js:56]: Original code is `== null`, the opposite should be `!= null`
```suggestion
      this.subscriberCount = this.data.subscribers != null ? this.data.subscribers.replace(/ subscriber(s)?/, '') : ''
```

**Review by PikachuEXE — CHANGES_REQUESTED** [review]

File: src/renderer/components/ft-list-channel/ft-list-channel.js (hunk 3 above)
Comment (Rikthepixel) [reply src/renderer/components/ft-list-channel/ft-list-channel.js]: Thanks, that could have caused a nasty bug. It should be fixed in the latest commit

File: src/renderer/components/watch-video-info/watch-video-info.js (hunk 2 above)
Comment (Rikthepixel) [reply src/renderer/components/watch-video-info/watch-video-info.js]: I'm sorry, that must have been my auto-formatting. 

Fixed it in the latest commit 👍

File: src/renderer/components/watch-video-info/watch-video-info.js (hunk 1 above)
Comment (Rikthepixel) [reply src/renderer/components/watch-video-info/watch-video-info.js]: I reversed the naming change. I thought it'd be a good change since in other places it is called subCount, though good point, it is out of scope.

Fixed this in the latest commit

**Review by PikachuEXE — APPROVED** [review]
Tested locally

File: src/renderer/components/ft-list-channel/ft-list-channel.js [hunk 4]
```diff
@@ -53,11 +53,8 @@ export default defineComponent({
 
       this.channelName = this.data.name
       this.id = this.data.id
-      if (this.hideChannelSubscriptions || this.data.subscribers == null) {
-        this.subscriberCount = null
-      } else {
-        this.subscriberCount = this.data.subscribers.replace(/ subscriber(s)?/, '')
-      }
+      this.subscriberCount = this.data.subscribers != null ? this.data.subscribers.replace(/ subscriber(s)?/, '') : ''
```
Comment (absidue) [inline src/renderer/components/ft-list-channel/ft-list-channel.js:56]: Probably best to keep this as `null` when there are no subscribers in the response, as that's what the Vue template uses to hide them from the UI. (see https://github.com/FreeTubeApp/FreeTube/pull/3692/files#diff-efe7580cfb6e0f2be7d806690c3c0460ed7c9d0b1fc7c72c4207824af09b6b73R29)
```suggestion
      this.subscriberCount = this.data.subscribers != null ? this.data.subscribers.replace(/ subscriber(s)?/, '') : null
```

Comment (Rikthepixel) [reply src/renderer/components/ft-list-channel/ft-list-channel.js]: Good catch, thank you

**Review by PikachuEXE — APPROVED** [review]

**Review by absidue — APPROVED** [review]

**Review by ChunkyProgrammer — APPROVED** [review]
