### PR TITLE
Fix/SearchHistoryDuplicate

### LINKED ISSUE #1659: [Bug] Text box for back button on top navbar shows "Forward"
**Behavior of the program**
The text box when mouse hovers on the back button on top navigation bar shows "Forward"

**Expected behavior**
The text box should show "Back" or "Backward"

**To Reproduce**
1. Open FreeTube
2. Hover mouse on back button on the top navigation bar
3. See error

**Screenshots**
https://imgur.com/a/odPfkTS

**Environment Information (please complete the following information):**
 - OS: Linux Mint
 - OS Version: 20.2
 - FreeTube version: v0.14.0 Beta
 - Installation Method (If applicable): .deb
 - Primary API Used: Invidious API

**Additional context**
https://github.com/FreeTubeApp/FreeTube/blob/818fa687f350969e3862ba00a4b052b15418611b/src/renderer/components/top-nav/top-nav.js#L64

The return value references a string (Backward) that doesn't exist, it should reference "Back" or the string will have to be renamed to "Backward".

https://github.com/FreeTubeApp/FreeTube/blob/818fa687f350969e3862ba00a4b052b15418611b/static/locales/en-US.yaml#L29

### LINKED ISSUE #2123: [Bug]: Search cache duplicate when go back and forward history
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Mentioned in https://github.com/FreeTubeApp/FreeTube/pull/2087#issuecomment-1065892574
> search ltt >
click on fetch more results >
wait a few seconds >
press the backward button on the left top side of the screen >
press the forward button on the left top side of the screen >
see duplicated videos/channel

The result is [Page1] [Page1] [Page2] ...
Happens both Local API and Invidious

### Expected Behavior

[Page1] [Page2] ...

### Issue Labels

visual bug

### FreeTube Version

v0.16.0

### Operating System Version

Windows 10 21H1

### Installation Method (If applicable)

_No response_

### Last Known Working FreeTube Version (If Any)

_No response_

### Primary API used

_No response_

### Additional Information

First Page

Fetch more results

History back & forward

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

### PR DESCRIPTION
**Pull request by hockerschwan**
Title
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
closes #2123
closes #1659

**Description**
Fix `addToSessionSearchHistory` in utils.js
(`payload.data` is already concatenated in Search.js)

**Screenshots (if appropriate)**
First page

No duplicates

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?
Please describe shortly how you tested it and whether there are any ramifications remaining. 
>search ltt >
click on fetch more results >
wait a few seconds >
press the backward button on the left top side of the screen >
press the forward button on the left top side of the screen >
see duplicated videos/channel

**Desktop (please complete the following information):**
 - OS: Windows10
 - OS Version: 21H1
 - FreeTube version: 0.16.0

### CODE REVIEW

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Also closes https://github.com/FreeTubeApp/FreeTube/issues/1659

File: src/renderer/components/top-nav/top-nav.js [hunk 1]
```diff
@@ -69,7 +69,7 @@ export default Vue.extend({
     },
 
     backwardText: function () {
-      return this.$t('Backward')
```
Comment (efb4f5ff-1298-471a-8973-3d47447115dc) [inline src/renderer/components/top-nav/top-nav.js:72]: would like to see this reverted to Backward

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — CHANGES_REQUESTED** [review]
everything lgtm only have one request

File: src/renderer/components/top-nav/top-nav.js (hunk 1 above)
Comment (ChunkyProgrammer) [reply src/renderer/components/top-nav/top-nav.js:72]: There's currently no translation for "Backward" in the locale file but there is one for "Back" and it's in relation to the nav-bar. https://github.com/FreeTubeApp/FreeTube/blob/1e1a04c81f256384071a520fd78f5146711810db/static/locales/en-US.yaml#L29

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by ChunkyProgrammer — APPROVED** [review]
lgtm

**Review by PikachuEXE — APPROVED** [review]
