### PR TITLE
Fix: Don't repeat comment replies

### LINKED ISSUE #1985: Duplicates of comment replies
**Behavior of the program**
In the comment section, when you click "View * replies" more than once during the time it takes to fetch the comments, FreeTube will display the fetched comments with as many duplicates as you clicked "View * replies".

**Expected behavior**
For FreeTube to only display the fetched comments once.
Alternatively one might double click because you quickly regretted your decision to view the replies, and thus would expect FreeTube to hide the replies.

**To Reproduce**
1. Use Local API
2. Go to any video that has comments with replies
3. Click "Click to View Comments"
4. Click on "View * replies" more than once during the time it takes to fetch the comments
5. See the error in how the fetched replies are displayed

**Environment Information:**
 - OS: Fedora
 - OS Version: Fedora 34 (Workstation Edition)
 - FreeTube version: v0.15.1-nightly-1377 Beta
 - Installation Method: .rpm
 - Primary API Used: Local API, this bug does not appear when using the Invidious API

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
---
Don't repeat comments
---

**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
closes #1985

**Description**
Please write a clear and concise description of what the pull request does.
This pr will stop the comment reply list from getting appended to if the last comment in the list has the same id as the last comment in the current request.

**Testing (for code that is not small enough to be easily understandable)**
Has this pull request been tested?

Yes, I spam clicked the view replies button

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: Latest nightly

### CODE REVIEW

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]
LGTM!

File: src/renderer/components/watch-video-comments/watch-video-comments.js [hunk 1]
```diff
@@ -274,9 +274,13 @@ export default Vue.extend({
...
       if (index !== null) {
-        this.commentData[index].replies = this.commentData[index].replies.concat(commentData)
-        this.commentData[index].replyToken = response.continuation
-        this.commentData[index].showReplies = true
+        if (this.commentData[index].replies.length === 0 || this.commentData[index].replies[this.commentData[index].replies.length - 1].commentId !== commentData[commentData.length - 1].commentId) {
+          this.commentData[index].replies = this.commentData[index].replies.concat(commentData)
+          this.commentData[index].replyToken = response.continuation
+          this.commentData[index].showReplies = true
+        } else {
+          console.log('Don\'t display comments twice')
```
Comment (PikachuEXE) [inline src/renderer/components/watch-video-comments/watch-video-comments.js:282]: Why do we need the log here :S

**Review by PikachuEXE — APPROVED** [review]

**Review by PrestonN — APPROVED** [review]
I'll go ahead and approve this, but I'll likely remove the console log
