### PR TITLE
Fix player full screen causing the app to start in full screen

### LINKED ISSUE #3220: [Bug]: FreeTube starts fullsrceen, and the "fullscreen" button cannot toggle between fullscreen modes
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open FreeTube
2. Observe that the app starts fullscreen. It takes the whole screen space, not leaving any space for the gnome bar or anything. This is different from starting maximized.
3. Toggle fullscreen mode by pressing super+M on Gnome (or maybe my gnome, can't remember if I changed this shortcut).
4. Observe that the app properly toggles fullscreen off.
5. Start a video, and play around with the "fullscreen" and "full window" buttons.
6. Observe that they act exactly the same. They do not toggle fullscreen mode, just makes the video take whatever available space the window already has.
7. Close FreeTube.
8. Start FreeTube again.
9. Observe 2. again. (So the app didn't remember the last state).

### Expected Behavior

The app starts not fullscreen, like all other apps.

The "full window" button toggles between using all the available space for the existing window for the video (this is currently working)

The "fullscreen" button toggles the window fullscreen, and uses all the available space for the video.

### Issue Labels

feature stopped working

### FreeTube Version

v0.18.0 Beta

### Operating System Version

Linux 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux

### Installation Method

.pacman

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

I can't remember, but it used to work months ago. I first thought the issue was with a Gnome extension.

### Additional Information

_No response_

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

### LINKED ISSUE #4534: [Bug]: App starts in fullscreen if you used fullscreen before quitting
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Watch any video in fullscreen
2. Quit the app with `ctrl+Q` or just closing the window but without quitting from fullscreen first.
3. run app again
4. it will start in fullscreen

### Expected Behavior

app resets to non-fullscreen on start

### Issue Labels

accessibility issue

### FreeTube Version

v0.19.1 Beta

### Operating System Version

fedora 39

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

_No response_

### Additional Information

_No response_

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

### PR DESCRIPTION
**Pull request by absidue**
# Fix player full screen causing the app to start in full screen

## Pull Request Type

- [x] Bugfix

## Related issue
- closes #4534
- closes #4649
- closes #3220

## Description
This is an alternative to https://github.com/FreeTubeApp/FreeTube/pull/4649 that should hopefully work more consistently (the creator of that pull request is aware that I am making this one).

When the app is closed while in full screen regardless of whether only the player or the entire window was full-screened, we save the full screen state and restore it at start up. For people that full-screened the app that is great, but for people that full-screened the player it's less desirable to have the entire app start in full screen.

### Full screen doesn't persist if player is full-screened
1. Open a video
2. Full screen the player, either through the button or the <kbd>F</kbd> hotkey
3. Close the app e.g. <kbd>Ctrl</kbd>+<kbd>Q</kbd> or <kbd>Alt</kbd>+<kbd>F4</kbd>
4. Open the app again and make sure it launches with normal window dimensions

### Full screen persists if you full screen the window (regression test)
1. Full screen the window e.g. <kbd>F11</kbd>
2. Close the app e.g. <kbd>Ctrl</kbd>+<kbd>Q</kbd> or <kbd>Alt</kbd>+<kbd>F4</kbd>
3. Open the app again and make sure it launches in full screen.

## Desktop

- **OS:** Windows
- **OS Version:** 11

### CODE REVIEW

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — COMMENTED** [review]
> ### Full screen doesn't persist if player is full-screened
> 1. Open a video
> 2. Full screen the player, either through the button or the <kbd>F</kbd> hotkey
> 3. Close the app e.g. <kbd>Ctrl</kbd>+<kbd>Q</kbd> or <kbd>Alt</kbd>+<kbd>F4</kbd>
> 4. Open the app again and make sure it launches with normal window dimensions

Works!

> ### Full screen persists if you full screen the window (regression test)
> 1. Full screen the window e.g. <kbd>F11</kbd>
> 2. Close the app e.g. <kbd>Ctrl</kbd>+<kbd>Q</kbd> or <kbd>Alt</kbd>+<kbd>F4</kbd>
> 3. Open the app again and make sure it launches in full screen.

Works!

### Full screen persists if you full screen the window and if player is fullscreened
1. Full screen the window e.g. <kbd>F11</kbd>
2. Full screen the player, either through the button or the <kbd>F</kbd> hotkey
3. Close the app e.g. <kbd>Ctrl</kbd>+<kbd>Q</kbd> or <kbd>Alt</kbd>+<kbd>F4</kbd>
4. Open the app again and make sure it launches in full screen.

App unfortunately doesn't launch in fullscreen, tested on win10

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
doesnt this also address https://github.com/FreeTubeApp/FreeTube/issues/3220?

File: src/main/index.js [hunk 1]
```diff
@@ -768,15 +770,28 @@ function runApp() {
       }
     })
 
+    newWindow.on('enter-html-full-screen', () => {
+      htmlFullscreenWindowIds.add(newWindow.id)
```
Comment (iacore) [inline src/main/index.js:774]: you can do `newWindow.htmlFullscreened = true` here, or is that too janky?

**Review by iacore — COMMENTED** [review]
LGTM

**Comment by PikachuEXE** [comment]
Seems working (test after merged with dev
Still WIP?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE 

> ### Full screen persists if you full screen the window and if player is fullscreened
> 1. Full screen the window e.g. <kbd>F11</kbd>
> 2. Full screen the player, either through the button or the <kbd>F</kbd> hotkey
> 3. Close the app e.g. <kbd>Ctrl</kbd>+<kbd>Q</kbd> or <kbd>Alt</kbd>+<kbd>F4</kbd>
> 4. Open the app again and make sure it launches in full screen.

> App unfortunately doesn't launch in fullscreen

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
maybe usefull chagpt prompt we 

Thanks for sharing the screenshot and the test cases. From what you're describing and what I see in the code diff, here's what's happening and how to fix the case where **both the window and the player are full-screened**:

---

## ✅ Current Fix (What the patch does):

The patch avoids **saving** fullscreen state if it was **triggered by the video player** (`htmlFullScreenWindowIds` tracks this). That works well for:

- Only player fullscreen → doesn't persist ✔️
- Only window fullscreen → does persist ✔️

---

## ❌ Failing Case:

> Both window **and** player are fullscreened → window fullscreen is ignored on next launch ❌

This happens because the `htmlFullScreenWindowIds` logic overrides the check and causes the app **not** to save the `window.fullScreen` state — even if it **was** actually fullscreen at the window level.

---

## 🛠️ Fix:

We need to detect whether **both** are true and ensure we still save the `window.fullScreen` state **if the window is in fullscreen**, **even if the player also was**.

### ✅ Fix Suggestion:

Replace this block:

```js
fullScreen: newWindow.isFullScreen() && !htmlFullScreen,
```

With something smarter like:

```js
const isWindowActuallyFullScreen = newWindow.isFullScreen();
const isHtmlFullScreen = htmlFullScreenWindowIds.has(newWindow.id);

// Save fullscreen only if it was true window fullscreen (not just player fullscreen)
fullScreen: isWindowActuallyFullScreen && !(isHtmlFullScreen && !newWindow.isMenuBarVisible()),
```

> `!newWindow.isMenuBarVisible()` is an example heuristic — adjust based on Electron API or UI clues if applicable.

---

## 🔍 Why This Works:

You're distinguishing between **true fullscreen** (like from F11) and **HTML fullscreen** (like a video player). If **both were active**, this check preserves the window's fullscreen status.

---

## ✅ Regression-Safe?

Yes, as long as `isFullScreen()` remains reliable and `htmlFullScreenWindowIds` is properly maintained.

---

Let me know your platform or Electron version if you want help refining this logic further.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@PikachuEXE PR is blocked due to https://github.com/FreeTubeApp/FreeTube/pull/5138#issuecomment-2933079077

All issues relating to this are about people being confused why the app is in fullscreen and apparently dont know how to unfullscreen it

What do you think of the following proposal:

Merge PR as is which would mean that in the case of "Full screen persists if you full screen the window and if player is fullscreened" that people at least know how to get back into fullscreen

Which is at least better than having the current situation

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by PikachuEXE — APPROVED** [review]
On macOS I need to toggle window fullscreen via menu
No idea what's the hotkey (I don't use this usually

**Review by ChunkyProgrammer — APPROVED** [review]
