### PR TITLE
Feedback when copying playlist link

### LINKED ISSUE #1351: Playlist page: No user feedback on copy link
**Behavior of the program**
On the playlist page when u go to share playlist and click on copy youtube/invidous link, the link will get copied, but the user doesn't get user feedback like the link has been copied.

**Expected behavior**
Receive the notification that the link has been copied.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to https://youtube.com/playlist?list=PLy6N_9yB8Qwy6LL0J7zLUyW8XNX-BPeDl
2. Hover above share playlist
3. Click on copy youtube/invidous link
4. No user feedback but u do get the link

**Link to video**

https://user-images.githubusercontent.com/73130443/119911710-5ab10300-bf49-11eb-9435-b2104ce6f06c.mp4

**Screenshots**
None.

**Environment Information (please complete the following information):**

- OS: [Win 10]
- OS Version: [20h2]
- FreeTube version: [v0.13.0-nightly-859 Beta]
- Installation Method (If applicable): [Portable]
- Primary API Used: [Local API]

**Additional context**
None.

### PR DESCRIPTION
**Pull request by no-comma**
**Pull Request Type**
Please select what type of pull request this is:
- [x] Bugfix
- [ ] Feature Implementation

**Related issue**
Fixes #1351

**Description**
When copying the link of a playlist FreeTube doesn't show any feedback to the user that the link has been copied like it does when copying a video URL. This PR makes it show the "URL copied to clipboard" message when copying playlist links.

**Screenshots (if appropriate)**
Before

https://user-images.githubusercontent.com/73130443/119911710-5ab10300-bf49-11eb-9435-b2104ce6f06c.mp4

After

https://user-images.githubusercontent.com/82644961/132214284-d6db1b65-c554-4cb0-ab9c-914a178139f8.mp4

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - FreeTube version: Based on be58077

### CODE REVIEW

File: src/renderer/components/playlist-info/playlist-info.js [hunk 1]
```diff
@@ -99,12 +99,18 @@ export default Vue.extend({
 
       switch (method) {
         case 'copyYoutube':
+          this.showToast({
+            message: this.$t('Share.YouTube URL copied to clipboard')
+          })
           navigator.clipboard.writeText(youtubeUrl)
```
Comment (ChunkyProgrammer) [inline src/renderer/components/playlist-info/playlist-info.js:105]: Maybe move the toast to after the clipboard gets written to?

File: src/renderer/components/playlist-info/playlist-info.js [hunk 2]
```diff
@@ -99,12 +99,18 @@ export default Vue.extend({
...
           break
         case 'openYoutube':
           this.openExternalLink(youtubeUrl)
           break
         case 'copyInvidious':
+          this.showToast({
+            message: this.$t('Share.Invidious URL copied to clipboard')
+          })
           navigator.clipboard.writeText(invidiousUrl)
```
Comment (ChunkyProgrammer) [inline src/renderer/components/playlist-info/playlist-info.js:114]: Same thing here

File: src/renderer/components/playlist-info/playlist-info.js (hunk 1 above)
Comment (no-comma) [reply src/renderer/components/playlist-info/playlist-info.js:105]: Sure, makes sense.

**Review by ChunkyProgrammer — APPROVED** [review]

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — APPROVED** [review]

**Review by jasonhenriquez — APPROVED** [review]
